use_default_settings: true

server:
  secret_key: "0d73800d9c6a879368a0992150de99ee5893adc46d068dc55e7ac6db1466b248"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

redis:
  url: redis://redis:6379/0
